version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techx_todo
    ports:
      - "3306:3306"
    volumes:
      - ./backend/sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge